
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           /:title

# Setup
timezone:            your timezone # eg. Asia/Kathmandu
locale:              en_us # eg. en_us
name:				         Drunking Games
title:               Drunking Games
tagline:             'Drunking Games is home to custom made drinking games.'
description:         'We handcraft all of our custom drinking games to give the users a fun drinking experience.'
url:                 site url
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Jordan
  url:            	 http://jns6971.com/
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 8008

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
